import type { VerdictViewModel } from "@/components/VerdictView";

export const EXAMPLE_VERDICT: VerdictViewModel = {
  title: "下沉市场冷冻预制菜社区团购",
  grade: "B",
  verdict: "投入五十万，窗口已过半，回报算不清，不建议做。",
  weighted: 5.4,
  customized: false,
  roiCalc: "按客单价 39、毛利率 18%、获客 12-25 元测算，回本依赖持续补贴，18 个月内期望值为负。",
  dimensions: [
    {
      key: "market",
      name: "市场空间",
      score: 6.3,
      confidence: "high",
      conclusion: "预制菜零售仍是十亿级以上市场，但社区团购渠道本身在收缩。规模在，渠道不在。",
    },
    {
      key: "competition",
      name: "竞争格局",
      score: 4.8,
      confidence: "high",
      conclusion: "兴盛优选收缩后留下的不是空白，是被美团优选与本地批发商重新填上的红海。错位空隙窄。",
    },
    {
      key: "timing",
      name: "入场时机",
      score: 3.6,
      confidence: "low",
      conclusion: "社区团购红利尾声。获客成本已不是 2020 年的数字。⚠ 低置信度：热度指数缺少第二官方源。",
      penalized: ["交叉验证不足，分数 ×0.9"],
    },
    {
      key: "fit",
      name: "公司匹配度",
      score: 0,
      confidence: "low",
      conclusion: "未评估",
      skipped: true,
    },
    {
      key: "roi",
      name: "投入产出比",
      score: 3.2,
      confidence: "high",
      conclusion: "冷链损耗 + 团长佣金 + 退货，把 18% 毛利吃掉后几乎没有安全边际。最坏情况不会立刻打死公司，但会持续失血。",
    },
  ],
  evidence: [
    {
      id: "e_demo01",
      dimension: "market",
      claim: "中国预制菜市场公开口径多在千亿级，零售端增速已从高位回落。",
      sourceName: "艾瑞咨询公开摘要",
      sourceUrl: "https://www.iresearch.com.cn/",
      fetchedAt: "2026-08-16T10:00:00.000Z",
      snapshot: "公开摘要将预制菜拆为 B 端餐饮与 C 端零售。C 端增速显著低于 2021-2022 年叙事。",
      crossValidated: true,
      confidence: "high",
      sourceLevel: "media",
    },
    {
      id: "e_demo02",
      dimension: "market",
      claim: "限额以上超市与粮油食品类零售可作需求底仓，但不能直接等于社区团购 GMV。",
      sourceName: "国家统计局",
      sourceUrl: "https://www.stats.gov.cn/",
      fetchedAt: "2026-08-16T10:01:00.000Z",
      snapshot: "社零分类口径与社区团购渠道销售额不可直接换算，报告据此降低「百亿赛道」口号的可信度。",
      crossValidated: true,
      confidence: "high",
      sourceLevel: "official",
    },
    {
      id: "e_demo03",
      dimension: "roi",
      claim: "生鲜电商公开财务中，履约费用率长期高位，补贴撤退后亏损暴露。",
      sourceName: "上市公司财报/巨潮资讯",
      sourceUrl: "https://www.cninfo.com.cn/",
      fetchedAt: "2026-08-16T10:02:00.000Z",
      snapshot: "可比公司在冷链与最后一公里上的费用结构，不支持 6 个月内回本假设。",
      crossValidated: true,
      confidence: "high",
      sourceLevel: "official",
    },
  ],
  opinions: [
    {
      dimension: "roi",
      persona: "taleb",
      stance: "oppose",
      argument: "别看均值回本故事。左尾是冷链断货、团长跑路、一季存货报废。你死不死？OK?",
      evidenceRefs: ["e_demo03"],
      round: "stance",
      experiential: false,
    },
    {
      dimension: "roi",
      persona: "buffett",
      stance: "oppose",
      argument: "护城河在变窄，不是变宽。这不像一座城堡，更像一场要不断续命的补贴比赛。",
      evidenceRefs: ["e_demo03"],
      round: "stance",
      experiential: false,
    },
    {
      dimension: "roi",
      persona: "facilitator",
      stance: "caveat",
      argument: "共识：安全边际不足。分歧：损失是慢性失血还是尾部暴击。收敛：按固定 rubric，投入产出比落入「测算为负或过长」档。",
      evidenceRefs: [],
      round: "synthesis",
      experiential: true,
    },
  ],
};
